---
  - name: update apt packages
    become: true
    yum:
      update_cache: true

  - name: upgrade packages
    become: true
    yum:
      name: "*"
      state: latest 

  - name: Fetch node nodules
    become: true
    #uri:  https://rpm.nodesource.com/setup_16.x
    shell: curl -sL https://rpm.nodesource.com/setup_10.x | sudo bash -

  - name: Install node
    become: true
    yum:
      name:
       - nodejs
#  - name: "install node dependencies"
#    become: true
#    yum:
#      name:
#       - nodejs
#       - npm # TODO: additional steps required before installing this
#      state: present
#      update_cache: true
  
  - name: install pm2
    become: true
    npm: 
      name: pm2
      global: true
      production: true
      state: present

  - name: "create ~/web"
    ansible.builtin.file:
      path: ~/web
      state: directory
      mode: '0755'

  - name: "copy files"
    copy:
      src: index.js
      dest: ~/web
      backup: true

  - name: "start server"
    shell: pm2 start ~/web/index.js -f